services:
  api:
    build:
      context: .
    ports:
      - "8080:8080"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    volumes:
      - api_data:/home/nonroot/.config
    tmpfs:
      - /tmp

volumes:
  api_data:
