services:
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      - chroma-data:/data
    ports:
      - "8000:8000"
    networks:
      - jandaira

  api:
    build:
      context: .
    depends_on:
      - chroma
    environment:
      - CHROMA_URL=http://chroma:8000
    ports:
      - "8080:8080"
    networks:
      - jandaira
    

networks:
  jandaira:
    driver: bridge

volumes:
  chroma-data: