server {
    # Define a porta customizada para o Nginx
    listen 9000;
    server_name localhost;

    # 1. Serve os arquivos estáticos do seu .tgz
    location / {
        root /usr/share/nginx/html/dist/;
        index index.html index.htm;
        
        # Muito útil se o seu site for React/Vue/Angular (Single Page Application)
        try_files $uri $uri/ /index.html; 
    }
}